# Check git status of nix configs
fetchNix() {(
    cd ~/.nix || exit 1
    git fetch --all --quiet
    GIT=$(git -c color.status=always status |
            grep -v -e "On branch" \
                -e "up to date" \
                -e 'use "git' \
                -e "nothing to commit")

    CHECK=$(echo "$GIT" | sed '/^$/d')

    if [ "$CHECK" != "" ]; then
        echo "$GIT"
        echo
    fi
)}

# Check for internet
if wget -q --spider https://git.nelim.org; then
    fetchNix
else
    echo "Offline"
fi

# Pokemon Sprite
pokemon-colorscripts -r 1-5
