# Check git status of nix configs
(
    cd ~/.nix || exit 1
    git fetch --all > /dev/null
    GIT=$(git -c color.status=always status |
            grep -v -e branch \
                -e 'use "git' \
                -e "nothing to commit" |
            sed '/^$/d')

    if [ "$GIT" != "" ]; then
        echo "$GIT"
        echo
    fi
)

# Pokemon Sprite
[ -x "$(command -v pokemon-colorscripts)" ] &&
[ "$POKE" == "true" ] &&
pokemon-colorscripts -r 1-5
