[project]
name = "coloryou"
description="Get Material You colors from an image."
version = "0.1.0"

dependencies = [
    "material_color_utilities_python",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
coloryou = "coloryou:main"
