[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "coloryou"
description="Get Material You colors from an image."
version = "0.1.0"

dependencies = [
    "material_color_utilities_python",
]
