name: Binary Cache

on: [push, pull_request, workflow_dispatch]

jobs:
  nix:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: https://github.com/actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup-Nix
      uses: https://github.com/cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.TOKEN_GH }}

    - name: Install-nixci
      uses: https://github.com/yaxitech/nix-install-pkgs-action@v3
      with:
        packages: "nixpkgs#nixci, dig"

    - name: Setup-cachix
      uses: https://github.com/cachix/cachix-action@v12
      with:
        name: archives
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Install SSH key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
        host='git.nelim.org'
        hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
        ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts

    - name: Build-configs
      run: |
        nix flake update
        nixci
