name: Binary Cache

on: [push, pull_request, workflow_dispatch]

jobs:
  nix:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: https://github.com/actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup-Nix
      uses: https://github.com/cachix/install-nix-action@v24

    - name: Install-nixci
      uses: https://github.com/yaxitech/nix-install-pkgs-action@v3
      with:
        packages: "nixpkgs#nixci"

    - name: Setup-cachix
      uses: https://github.com/cachix/cachix-action@v12
      with:
        name: archives
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build-configs
      run: |
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
        nix flake update
        nixci
