name: Discord

on:
  - workflow_dispatch
  - push

jobs:
  discord_commits:
    runs-on: nix-latest
    name: discord commits
    if: contains(github.event.head_commit.message, '(servers)')

    steps:
      - name: Discommit
        shell: bash
        run: nix run github:matt1432/discommit
        env:
          INPUT_DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          INPUT_API_URL: 'https://git.nelim.org/api/v1/repos/$OWNER/$REPO/git/commits/$REF'
          INPUT_TITLE: 'New commit containing changes to server configs:'
