# This file was autogenerated. DO NOT EDIT!
pkgs: {
  version = "1.1.0+e8218eb";
  src = pkgs.fetchFromGitHub {
    repo = "nix-serve-ng";
    owner = "aristanetworks";
    rev = "e8218eb1c912a800ea77ae7edd71db4ee379a7dd";
    hash = "sha256-H4PLUC9xb2kdDs4r/VaiRq7rrK/gM+WFuHnRIP78H+U=";
  };
}
