# This file was autogenerated. DO NOT EDIT!
pkgs: {
  version = "1.1.0+2c30a4d";
  src = pkgs.fetchFromGitHub {
    repo = "nix-serve-ng";
    owner = "aristanetworks";
    rev = "2c30a4d56da4e24021682b63e72ba92d4c4bf00a";
    hash = "sha256-ub+W3fQuVK2DV1WukRMBOGUdHIw84akUnujD2Vqbg68=";
  };
}
