# This file was autogenerated. DO NOT EDIT!
pkgs: {
  version = "1.1.0+f63998a";
  src = pkgs.fetchFromGitHub {
    repo = "nix-serve-ng";
    owner = "aristanetworks";
    rev = "f63998a6c81fab86e840dbab483d387dee5ffc0a";
    hash = "sha256-paUnCU08wDZ3bS0Fa4QhtjWMcpWgcTRwO/ee3wT28Nw=";
  };
}
