# This file was autogenerated. DO NOT EDIT!
{
  version = "2.35.0";
  url = "https://github.com/VueTorrent/VueTorrent/releases/download/v2.35.0/vuetorrent.zip";
  hash = "sha256-bgwOastWNxCq8yzRZc802g5dYbwaaDhuTPl6ZI+oFxw=";
}
