# This file was autogenerated. DO NOT EDIT!
{
  version = "2.33.0";
  url = "https://github.com/VueTorrent/VueTorrent/releases/download/v2.33.0/vuetorrent.zip";
  hash = "sha256-KV8XmrW7ErKX3sHPNIitgV4cB6lzfAOAzLBusxYfVfM=";
}
