# This file was autogenerated. DO NOT EDIT!
{
  version = "2.34.1";
  url = "https://github.com/VueTorrent/VueTorrent/releases/download/v2.34.1/vuetorrent.zip";
  hash = "sha256-bPDyxlM4NWArHRjNJug5JtU8kzDg6Jjpca9oUCM9IOs=";
}
