# This file was autogenerated. DO NOT EDIT!
{
  version = "2.29.0";
  url = "https://github.com/VueTorrent/VueTorrent/releases/download/v2.29.0/vuetorrent.zip";
  hash = "sha256-F8aKEZAYjdZEnIUjwEY1rNkcN59kFtH4bkK09AwnIHg=";
}
