# This file was autogenerated. DO NOT EDIT!
{
  version = "2.31.3";
  url = "https://github.com/VueTorrent/VueTorrent/releases/download/v2.31.3/vuetorrent.zip";
  hash = "sha256-JiVFROakYegX5y4Ox/LV2L+SdZbJA6xYtuCxZjpJtVY=";
}
