# This file was autogenerated. DO NOT EDIT!
{
  version = "2.31.2";
  url = "https://github.com/VueTorrent/VueTorrent/releases/download/v2.31.2/vuetorrent.zip";
  hash = "sha256-Y3LyWScO9Vkod7dqEM7E4qhPHWzz6D4u7cebc+AIMvo=";
}
