# This file was autogenerated. DO NOT EDIT!
{
  version = "2.13.0";
  url = "https://github.com/VueTorrent/VueTorrent/releases/download/v2.13.0/vuetorrent.zip";
  hash = "sha256-ZdK8PjvH/QQoG7Ft/2MGaHyz/ifhUFEpai532XVOCh8=";
}
