# This file was autogenerated. DO NOT EDIT!
{
  version = "2.11.1";
  url = "https://github.com/VueTorrent/VueTorrent/releases/download/v2.11.1/vuetorrent.zip";
  hash = "sha256-yxvs2xbH0ReLrSx+ERLbLMAQv/6W5208WnMz3X4lhHA=";
}
