# This file was autogenerated. DO NOT EDIT!
{
  version = "2.9.0";
  url = "https://github.com/VueTorrent/VueTorrent/releases/download/v2.9.0/vuetorrent.zip";
  hash = "sha256-XrRfgxmRkbyi8FMXL6Pjltyawzr4SS2Gb4/Kz38tnkk=";
}
