import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { styleText } from 'node:util';

import { parseNurl } from './lib';

/* Constants */
const FLAKE = process.env.FLAKE;

const genSrcText = (
    version: string,
    hash: string,
    rev: string,
) => `# This file was autogenerated. DO NOT EDIT!
pkgs: {
  version = "${version}";
  src = pkgs.fetchFromGitHub {
    repo = "nix-serve-ng";
    owner = "aristanetworks";
    rev = "${rev}";
    hash = "${hash}";
  };
}
`;

const SHORT_REV_N = 7;

export default (): string | null => {
    console.log(styleText(['magenta'], '\nUpdating nix-serve-ng:\n'));

    const FILE = `${FLAKE}/overlays/nix-version/nix-serve-ng-src.nix`;

    const oldVersion = JSON.parse(
        spawnSync(
            [
                'nix',
                'eval',
                '-f',
                FILE,
                "--apply 'x: (x {}).version'",
                '--json',
            ].join(' '),
            [],
            { shell: true },
        ).stdout.toString(),
    );

    const tag = spawnSync(
        "curl -sL https://github.com/aristanetworks/nix-serve-ng/raw/refs/heads/main/nix-serve-ng.cabal | sed -n 's/^version:[ ]*\\(.*\\)/\\1/p'",
        [],
        { shell: true },
    )
        .stdout.toString()
        .replaceAll('\n', '');

    const {
        args: { hash, rev },
    } = parseNurl('https://github.com/aristanetworks/nix-serve-ng');

    const version = `${tag}+${rev.substring(0, SHORT_REV_N)}`;

    const fileText = genSrcText(version, hash, rev);

    writeFileSync(FILE, fileText);

    return oldVersion !== version
        ? `nix-serve-ng: ${oldVersion} -> ${version}\n`
        : null;
};
