import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { styleText } from 'node:util';

import { parseFetchurl } from './lib';

/* Constants */
const FLAKE = process.env.FLAKE;

const genVueText = (
    version: string,
    hash: string,
    url: string,
) => `# This file was autogenerated. DO NOT EDIT!
{
  version = "${version}";
  url = "${url}";
  hash = "${hash}";
}
`;

export default (): string | null => {
    console.log(styleText(['magenta'], '\nUpdating Vuetorrent:\n'));

    const FILE = `${FLAKE}/configurations/nos/modules/docker/media/qbit/vuetorrent.nix`;

    const OLD_VERSION = JSON.parse(
        spawnSync(['nix', 'eval', '-f', FILE, '--json'].join(' '), [], {
            shell: true,
        }).stdout.toString(),
    ).version;

    const VERSION = JSON.parse(
        spawnSync(
            [
                'curl',
                '-s',
                'https://api.github.com/repos/VueTorrent/VueTorrent/releases/latest',
            ].join(' '),
            [],
            { shell: true },
        ).stdout.toString(),
    ).tag_name.replace('v', '');

    const URL = `https://github.com/VueTorrent/VueTorrent/releases/download/v${VERSION}/vuetorrent.zip`;

    let hash: string | undefined = undefined;
    try {
        hash = parseFetchurl(URL);
    }
    catch (e) {
        console.error(URL);
        console.error(e);
    }

    if (!hash) {
        return null;
    }

    const fileText = genVueText(VERSION, hash, URL);

    writeFileSync(FILE, fileText);

    return OLD_VERSION !== VERSION
        ? `Vuetorrent: ${OLD_VERSION} -> ${VERSION}\n`
        : null;
};
