# This file was autogenerated. DO NOT EDIT!
{
  plugins = {
    cloudflare = {
      url = "github.com/caddy-dns/cloudflare";
      version = "v0.0.0-20250228175314-1fb64108d4de";
    };
  };

  hash = "sha256-YYpsf8HMONR1teMiSymo2y+HrKoxuJMKIea5/NEykGc=";
}
