# This file was autogenerated. DO NOT EDIT!
{
  plugins = {
    cloudflare = {
      url = "github.com/caddy-dns/cloudflare";
      version = "v0.0.0-20240703190432-89f16b99c18e";
    };
  };

  hash = "sha256-JoujVXRXjKUam1Ej3/zKVvF0nX97dUizmISjy3M3Kr8=";
}
