# This file was autogenerated. DO NOT EDIT!
{
  plugins = {
    cloudflare = {
      url = "github.com/caddy-dns/cloudflare";
      version = "v0.0.0-20250214163716-188b4850c0f2";
    };
  };

  hash = "sha256-dYZvFCSuDsOAYg8GgkdpulIzFud9EmP9mS81c87sOoY=";
}
