#!/bin/bash

## https://www.reddit.com/r/swaywm/comments/ocec7k/comment/i93s0ma/
## https://git.sr.ht/~mil/lisgd/tree/0.3.7/item/config.def.h

function gestures {
	lisgd -d /dev/input/by-path/platform-AMDI0010\:00-event -o 0 -t 125 -r 25 -m 3200 \
	-g "3,RL,N,S,R,$HOME/.config/sway/scripts/gestures.sh next" \
	-g "3,LR,N,S,R,$HOME/.config/sway/scripts/gestures.sh prev"
}

if pgrep lisgd ; then
	killall lisgd
	gestures
else
	gestures
fi
