#!/bin/bash

## https://www.reddit.com/r/swaywm/comments/ocec7k/comment/i93s0ma/
## https://git.sr.ht/~mil/lisgd/tree/0.3.7/item/config.def.h

function gestures {
	lisgd -d /dev/input/by-path/platform-AMDI0010\:00-event -o 0 -t 125 -r 25 -m 3200 \
	-g "1,UD,B,*,R,bash -c 'busctl call --user sm.puri.OSK0 /sm/puri/OSK0 sm.puri.OSK0 SetVisible b false'" \
	-g "1,DU,B,*,R,bash -c 'busctl call --user sm.puri.OSK0 /sm/puri/OSK0 sm.puri.OSK0 SetVisible b true'" \
	-g "3,RL,N,*,R,$HOME/.config/hypr/scripts/gestures.sh next touch" \
	-g "3,LR,N,*,R,$HOME/.config/hypr/scripts/gestures.sh prev touch"

}

if pgrep lisgd ; then
	killall lisgd
	gestures
else
	gestures
fi
