# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "Cronos";
    version = "0.9.0";
    hash = "sha256-yDYBfqSXqvT/VPUf6UT3XOgqqPmOMYqhjCBxpF5i15c=";
  })
  (fetchNuGet {
    pname = "FuzzySharp";
    version = "2.0.2";
    hash = "sha256-GuWqVOo+AG8MSvIbusLPjKfJFQRJhSSJ9eGWljTBA/c=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "3.3.4";
    hash = "sha256-qDzTfZBSCvAUu9gzq2k+LOvh6/eRvJ9++VCNck/ZpnE=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "4.12.0";
    hash = "sha256-mm/OKG3zPLAeTVGZtuLxSG+jpQDOchn1oyHqBBJW2Ho=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "4.12.0";
    hash = "sha256-m1i1Q5pyEq4lAoYjNE9baEjTplH8+bXx5wSA+eMmehk=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "9.0.0";
    hash = "sha256-uBLeb4z60y8z7NelHs9uT3cLD6wODkdwyfJm6/YZLDM=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "9.0.0";
    hash = "sha256-xtG2USC9Qm0f2Nn6jkcklpyEDT3hcEZOxOwTc0ep7uc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "9.0.0";
    hash = "sha256-6ajYWcNOQX2WqftgnoUmVtyvC1kkPOtTCif4AiKEffU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.CommandLine";
    version = "9.0.0";
    hash = "sha256-RE6DotU1FM1sy5p3hukT+WOFsDYJRsKX6jx5vhlPceM=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.EnvironmentVariables";
    version = "9.0.0";
    hash = "sha256-tDJx2prYZpr0RKSwmJfsK9FlUGwaDmyuSz2kqQxsWoI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.FileExtensions";
    version = "9.0.0";
    hash = "sha256-PsLo6mrLGYfbi96rfCG8YS1APXkUXBG4hLstpT60I4s=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Json";
    version = "9.0.0";
    hash = "sha256-qQn7Ol0CvPYuyecYWYBkPpTMdocO7I6n+jXQI2udzLI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.UserSecrets";
    version = "9.0.0";
    hash = "sha256-GoEk+Qq7lbiwWurHYx1LkDaUzIpOzaoTiVGDPfViGak=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "9.0.0";
    hash = "sha256-dAH52PPlTLn7X+1aI/7npdrDzMEFPMXRv4isV1a+14k=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "9.0.0";
    hash = "sha256-CncVwkKZ5CsIG2O0+OM9qXuYXh3p6UGyueTHSLDVL+c=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyModel";
    version = "9.0.0";
    hash = "sha256-xirwlMWM0hBqgTneQOGkZ8l45mHT08XuSSRIbprgq94=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics";
    version = "9.0.0";
    hash = "sha256-JMbhtjdcWRlrcrbgPlowfj26+pM+MYhnPIaYKnv9byU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.Abstractions";
    version = "9.0.0";
    hash = "sha256-wG1LcET+MPRjUdz3HIOTHVEnbG/INFJUqzPErCM79eY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "9.0.0";
    hash = "sha256-mVfLjZ8VrnOQR/uQjv74P2uEG+rgW72jfiGdSZhIfDc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Physical";
    version = "9.0.0";
    hash = "sha256-IzFpjKHmF1L3eVbFLUZa2N5aH3oJkJ7KE1duGIS7DP8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileSystemGlobbing";
    version = "9.0.0";
    hash = "sha256-eBLa8pW/y/hRj+JbEr340zbHRABIeFlcdqE0jf5/Uhc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting";
    version = "9.0.0";
    hash = "sha256-apIN4Cz86ujsMp/ibxcvguA9uCFaFqOsZ4kAUPX5ASI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.Abstractions";
    version = "9.0.0";
    hash = "sha256-NhEDqZGnwCDFyK/NKn1dwLQExYE82j1YVFcrhXVczqY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Http";
    version = "9.0.0";
    hash = "sha256-MsStH3oUfyBbcSEoxm+rfxFBKI/rtB5PZrSGvtDjVe0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "9.0.0";
    hash = "sha256-kR16c+N8nQrWeYLajqnXPg7RiXjZMSFLnKLEs4VfjcM=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "9.0.0";
    hash = "sha256-iBTs9twjWXFeERt4CErkIIcoJZU1jrd1RWCI8V5j7KU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Configuration";
    version = "9.0.0";
    hash = "sha256-ysPjBq64p6JM4EmeVndryXnhLWHYYszzlVpPxRWkUkw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Console";
    version = "9.0.0";
    hash = "sha256-N2t9EUdlS6ippD4Z04qUUyBuQ4tKSR/8TpmKScb5zRw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Debug";
    version = "9.0.0";
    hash = "sha256-5W6fP9Eb98U3MTWKeLzSNl2cRFpE694OOPjpWp/qTAk=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.EventLog";
    version = "9.0.0";
    hash = "sha256-mIL1I85Ef5+/mXl24odoUpcXet+jCZTRtKCd5z6YUwI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.EventSource";
    version = "9.0.0";
    hash = "sha256-pplZskMsR3gGbs3I0wycGsvIMPIpfWFJpOsR9GkiYRw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "9.0.0";
    hash = "sha256-DT5euAQY/ItB5LPI8WIp6Dnd0lSvBRP35vFkOXC68ck=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options.ConfigurationExtensions";
    version = "9.0.0";
    hash = "sha256-r1Z3sEVSIjeH2UKj+KMj86har68g/zybSqoSjESBcoA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "9.0.0";
    hash = "sha256-ZNLusK1CRuq5BZYZMDqaz04PIKScE2Z7sS2tehU7EJs=";
  })
  (fetchNuGet {
    pname = "NetDaemon.AppModel";
    version = "24.50.0";
    hash = "sha256-jnDy2tY+ENXlPmFX+RJjRep2oxQVGKE6+YX4SSn1xdw=";
  })
  (fetchNuGet {
    pname = "NetDaemon.AppModel.SourceDeployedApps";
    version = "24.50.0";
    hash = "sha256-JujSAc1nrFBlqLyb1a+9WX7s2OuQSZU8IsHltmhRiqs=";
  })
  (fetchNuGet {
    pname = "NetDaemon.Client";
    version = "24.50.0";
    hash = "sha256-BEl4scUdhRU812VHD7sLo1GrK/cN5Ion+IkgSC9L+wY=";
  })
  (fetchNuGet {
    pname = "NetDaemon.Extensions.Logging";
    version = "24.50.0";
    hash = "sha256-RoaYCHv4XBwqyoWSCflO1OrB0/Tdu8sMRSIBYSpIbSs=";
  })
  (fetchNuGet {
    pname = "NetDaemon.Extensions.Scheduling";
    version = "24.50.0";
    hash = "sha256-JKIpaayGcC37RaAoQG4M5yYPlAIpAkrd7LFMuB80G04=";
  })
  (fetchNuGet {
    pname = "NetDaemon.Extensions.Tts";
    version = "24.50.0";
    hash = "sha256-5tEto2kdRjBHhr8xudtAzn2G6VIfSVIcgB3VMw4/BFY=";
  })
  (fetchNuGet {
    pname = "NetDaemon.HassModel";
    version = "24.50.0";
    hash = "sha256-eTJF7FyBEYNo7XgYv/TKFrElt/hc8/is46q7daFilwo=";
  })
  (fetchNuGet {
    pname = "NetDaemon.HassModel.Integration";
    version = "24.50.0";
    hash = "sha256-L18wM0BezWld//RyLFf2yo3oyGd/DgbnbaxcpjxJF/s=";
  })
  (fetchNuGet {
    pname = "NetDaemon.Runtime";
    version = "24.50.0";
    hash = "sha256-vMrH+Zw107mGEbTIh/wjx4rxw378MezltqJ0mtuZ8lw=";
  })
  (fetchNuGet {
    pname = "Serilog";
    version = "4.0.0";
    hash = "sha256-j8hQ5TdL1TjfdGiBO9PyHJFMMPvATHWN1dtrrUZZlNw=";
  })
  (fetchNuGet {
    pname = "Serilog";
    version = "4.2.0";
    hash = "sha256-7f3EpCsEbDxXgsuhE430KVI14p7oDUuCtwRpOCqtnbs=";
  })
  (fetchNuGet {
    pname = "Serilog.AspNetCore";
    version = "9.0.0";
    hash = "sha256-h58CFtXBRvwhTCrhQPHQMKbp98YiK02o+cOyOmktVpQ=";
  })
  (fetchNuGet {
    pname = "Serilog.Extensions.Hosting";
    version = "9.0.0";
    hash = "sha256-bidr2foe7Dp4BJOlkc7ko0q6vt9ITG3IZ8b2BKRa0pw=";
  })
  (fetchNuGet {
    pname = "Serilog.Extensions.Logging";
    version = "9.0.0";
    hash = "sha256-aGkz1V4HVl0rWC1BkcnLhG1EC7WLBoT3tdLdUUTFXaw=";
  })
  (fetchNuGet {
    pname = "Serilog.Formatting.Compact";
    version = "3.0.0";
    hash = "sha256-nejEYqJEMG9P2iFZvbsCUPr5LZRtxbdUTLCI9N71jHY=";
  })
  (fetchNuGet {
    pname = "Serilog.Settings.Configuration";
    version = "9.0.0";
    hash = "sha256-Q/q5UiSrcxoy5a/orod20E2RfiRtHDhxjjGMe1dW35I=";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.Console";
    version = "6.0.0";
    hash = "sha256-QH8ykDkLssJ99Fgl+ZBFBr+RQRl0wRTkeccQuuGLyro=";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.Debug";
    version = "3.0.0";
    hash = "sha256-7/LmoRF1rUDFhJ47bTRQQFRgSHnZDO8484r3sCGqYvE=";
  })
  (fetchNuGet {
    pname = "Serilog.Sinks.File";
    version = "6.0.0";
    hash = "sha256-KQmlUpG9ovRpNqKhKe6rz3XMLUjkBqjyQhEm2hV5Sow=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "8.0.0";
    hash = "sha256-F7OVjKNwpqbUh8lTidbqJWYi476nsq9n+6k0+QVRo3w=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "9.0.0";
    hash = "sha256-tPvt6yoAp56sK/fe+/ei8M65eavY2UUhRnbrREj/Ems=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "9.0.0";
    hash = "sha256-vb0NrPjfEao3kfZ0tavp2J/29XnsQTJgXv3/qaAwwz0=";
  })
  (fetchNuGet {
    pname = "System.Reactive";
    version = "6.0.1";
    hash = "sha256-Lo5UMqp8DsbVSUxa2UpClR1GoYzqQQcSxkfyFqB/d4Q=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "8.0.0";
    hash = "sha256-dQGC30JauIDWNWXMrSNOJncVa1umR1sijazYwUDdSIE=";
  })
  (fetchNuGet {
    pname = "YamlDotNet";
    version = "16.2.1";
    hash = "sha256-Nu/rD43sihE4PTHC5r2Ua2gafclqcd2U95RcNFvGFhc=";
  })
]
